### ISSUE TITLE
A potentially dangerous Request.Path value was detected from the client

### ISSUE THREAD

**Issue by Aa-Koo** [hp-net/homebridge-nibe#151]
Hi. I get error message? What to do?
<img width="1889" alt="Näyttökuva 2022-12-11 kello 18 10 04" src="https://user-images.githubusercontent.com/120256162/206914916-cdab39c3-0f7f-4d58-bd81-f1921d3c011b.png">

**Comment by hpruszyn** [comment]
Hi, I remember similar issue. The problem was related to wrong parameters provided on settings page. Please check once again all values provided by you, especially system identifier copied from url.

**Comment by Aa-Koo** [comment]
> Hi, I remember similar issue. The problem was related to wrong parameters provided on settings page. Please check once again all values provided by you, especially system identifier copied from url.

I put many times everything again. Still not work. I have unistall plugin and re install it 3 times. Still same error. API have check, Generate new API and still same error.

**Comment by hpruszyn** [comment]
Does your system identifier look like:
` "systemIdentifier": "108159",`?

**Comment by Aa-Koo** [comment]
I'm idiot.. I put the whole system indentifies URL. Now i put only the numbers and everything works! 
Thank you!  I am grateful for your help!

**Comment by hpruszyn** [comment]
You welcome :-)
