### ISSUE TITLE
[Nibe] error from parameters

### ISSUE THREAD

**Issue by nseries100** [hp-net/homebridge-nibe#171]
Hi,
I`m getting this error below. No changes in configuration or homebridge or in network.

`[02/02/2023, 11:41:12] [Nibe] error from parameters?parameterIds=48132&parameterIds=47260&parameterIds=48857&parameterIds=48856&parameterIds=48855&parameterIds=48854&parameterIds=48853&parameterIds=47265&parameterIds=47264&parameterIds=47263&parameterIds=47262&parameterIds=47261&parameterIds=47011&parameterIds=48739&parameterIds=47374&systemUnitId=
[02/02/2023, 11:41:12] [Nibe] Error: [AxiosError: timeout of 45000ms exceeded] {
  code: 'ECONNABORTED',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 45000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'user-agent': 'fetcher.nibeuplink',
      Authorization: 'Bearer AAEAAECzbT471bOLV9_fs9eJYCFQaa42Se9XqkB2V6iULUxSm1G5TQLGSUzp8DqeFul_3lYMvDNlTiqyppnJP8Upw19lDM2yjA44hSmeRRvAxTMyCgG-BTfygE4rwkxTgGJNDenGMlvx3x2i7knj8rgK1jUFiUFy7a8r63D7IytdSzubXQiBiqR5VjoVW3eG39CCYTauqhZfVXNpW-of32DuE6cldlzJGyGcwvlrNuAKogQAazNnbdE-BJM7GLtMvggbQAUbNk7e2rB369iapsy6a8-17VDSkLQN7I648zjxRpe1yH9MnficqgjHgVIND9eJQrhbag5QQUxieBXtdemymK60AQAAAAEAADYQVjj5MeU74b1XIi8us5XOzzDfrkSXWZF8oxMESbRNgeTtelb6Et-7xciWhUWR8dM7VwV8RFmYyLqDIZYGc01YIgkuk7QiSPm7kCTy7BzDSfJCaAqDNMTO1zmYCsdcEruGP-Sxhrj3KFDQoId4qzhaw94beOz0ybOoDumMKaRa_fg312Bw0YFi-8nJYpL-A7GHQPIYF0t5TY8ZQYqR3pCHNFq8hU6086bquTTG5DXQkXRj9tCL1L4DRFxBXYL-OULiz-DvCr1KdmRzNl50jy2gG3KPZZMKW8bGIofNKTwvdmmEeiPxHaULQYrye9-_nw100f1-IsTSoPjb9DFXq6cf3oKkgosm6zSJ04e_4u9Wf9inRpw9n2ZLNd5x5L8kGTyZ3zWZz0xK_20hZ6VPNlrRKs82E_RAeX8wlMkoazMl7DTyn4H8jXTUXo65zY3wiwAuHFlpkeY37foZLZf6NPbHVeKJqLogLQTcq24gjHBen3pqq1bKBWCvvXZ1tVnZvlNkA1aIP3lG8xyDPDTJ9UJ3T9BHVs0d2JciWMraHjHtVA_rto7-M39bn9CkiYMJMg',
      'Accept-Language': 'en'
    },
    baseURL: 'https://api.nibeuplink.com',
    method: 'get',
    url: '/api/v1/systems/82004/parameters?parameterIds=48132&parameterIds=47260&parameterIds=48857&parameterIds=48856&parameterIds=48855&parameterIds=48854&parameterIds=48853&parameterIds=47265&parameterIds=47264&parameterIds=47263&parameterIds=47262&parameterIds=47261&parameterIds=47011&parameterIds=48739&parameterIds=47374&systemUnitId=',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Array]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/api/v1/systems/82004/parameters?parameterIds=48132&parameterIds=47260&parameterIds=48857&parameterIds=48856&parameterIds=48855&parameterIds=48854&parameterIds=48853&parameterIds=47265&parameterIds=47264&parameterIds=47263&parameterIds=47262&parameterIds=47261&parameterIds=47011&parameterIds=48739&parameterIds=47374&systemUnitId=',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'api.nibeuplink.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/api/v1/systems/82004/parameters',
      search: '?parameterIds=48132&parameterIds=47260&parameterIds=48857&parameterIds=48856&parameterIds=48855&parameterIds=48854&parameterIds=48853&parameterIds=47265&parameterIds=47264&parameterIds=47263&parameterIds=47262&parameterIds=47261&parameterIds=47011&parameterIds=48739&parameterIds=47374&systemUnitId='
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /api/v1/systems/82004/parameters?parameterIds=48132&parameterIds=47260&parameterIds=48857&parameterIds=48856&parameterIds=48855&parameterIds=48854&parameterIds=48853&parameterIds=47265&parameterIds=47264&parameterIds=47263&parameterIds=47262&parameterIds=47261&parameterIds=47011&parameterIds=48739&parameterIds=47374&systemUnitId= HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'user-agent: fetcher.nibeuplink\r\n' +
        'Authorization: Bearer AAEAAECzbT471bOLV9_fs9eJYCFQaa42Se9XqkB2V6iULUxSm1G5TQLGSUzp8DqeFul_3lYMvDNlTiqyppnJP8Upw19lDM2yjA44hSmeRRvAxTMyCgG-BTfygE4rwkxTgGJNDenGMlvx3x2i7knj8rgK1jUFiUFy7a8r63D7IytdSzubXQiBiqR5VjoVW3eG39CCYTauqhZfVXNpW-of32DuE6cldlzJGyGcwvlrNuAKogQAazNnbdE-BJM7GLtMvggbQAUbNk7e2rB369iapsy6a8-17VDSkLQN7I648zjxRpe1yH9MnficqgjHgVIND9eJQrhbag5QQUxieBXtdemymK60AQAAAAEAADYQVjj5MeU74b1XIi8us5XOzzDfrkSXWZF8oxMESbRNgeTtelb6Et-7xciWhUWR8dM7VwV8RFmYyLqDIZYGc01YIgkuk7QiSPm7kCTy7BzDSfJCaAqDNMTO1zmYCsdcEruGP-Sxhrj3KFDQoId4qzhaw94beOz0ybOoDumMKaRa_fg312Bw0YFi-8nJYpL-A7GHQPIYF0t5TY8ZQYqR3pCHNFq8hU6086bquTTG5DXQkXRj9tCL1L4DRFxBXYL-OULiz-DvCr1KdmRzNl50jy2gG3KPZZMKW8bGIofNKTwvdmmEeiPxHaULQYrye9-_nw100f1-IsTSoPjb9DFXq6cf3oKkgosm6zSJ04e_4u9Wf9inRpw9n2ZLNd5x5L8kGTyZ3zWZz0xK_20hZ6VPNlrRKs82E_RAeX8wlMkoazMl7DTyn4H8jXTUXo65zY3wiwAuHFlpkeY37foZLZf6NPbHVeKJqLogLQTcq24gjHBen3pqq1bKBWCvvXZ1tVnZvlNkA1aIP3lG8xyDPDTJ9UJ3T9BHVs0d2JciWMraHjHtVA_rto7-M39bn9CkiYMJMg\r\n' +
        'Accept-Language: en\r\n' +
        'Host: api.nibeuplink.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v1/systems/82004/parameters?parameterIds=48132&parameterIds=47260&parameterIds=48857&parameterIds=48856&parameterIds=48855&parameterIds=48854&parameterIds=48853&parameterIds=47265&parameterIds=47264&parameterIds=47263&parameterIds=47262&parameterIds=47261&parameterIds=47011&parameterIds=48739&parameterIds=47374&systemUnitId=',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.nibeuplink.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null,
      [Symbol(kError)]: undefined
    },
    _currentUrl: 'https://api.nibeuplink.com/api/v1/systems/82004/parameters?parameterIds=48132&parameterIds=47260&parameterIds=48857&parameterIds=48856&parameterIds=48855&parameterIds=48854&parameterIds=48853&parameterIds=47265&parameterIds=47264&parameterIds=47263&parameterIds=47262&parameterIds=47261&parameterIds=47011&parameterIds=48739&parameterIds=47374&systemUnitId=',
    _timeout: null,
    [Symbol(kCapture)]: false
  }
}`

**Comment by hpruszyn** [comment]
`timeout of 45000ms exceeded`

Hmm it looks like some kind of network issues. Can you telnet api.nibeuplink.com 443 from machine/docker that homebridge is running?

**Comment by nseries100** [comment]
Seems ok for me:
`pi@raspberrypi:~ $ telnet api.nibeuplink.com 443
Trying 20.73.204.29...
Connected to ssl.jpicloud-prod-api-new.azurewebsites.net.
Escape character is '^]'.`

**Comment by hpruszyn** [comment]
Is this still valid? If yes can you try to run it on a different machine in the same network? - we will check if it's a network or machine problem.

**Comment by nseries100** [comment]
Yes, its valid. I dont have another machine. It shoudnt be network problem. I have dozens of iot devices at home on wifi with no problem at all.
