### ISSUE TITLE
How to get Auth code?

### ISSUE THREAD

**Issue by Stanly001CZ** [hp-net/homebridge-nibe#181]
Hi guys, plese could you help me to get auth code? I am absolutely lost. I use https://www.npmjs.com/package/iobroker.nibeuplink for getting others information but Auth Code still missing. Thank you so much

**Comment by hpruszyn** [comment]
https://api.nibeuplink.com/oauth/authorize?response_type=code&client_id=XXXXXX&scope=READSYSTEM%20WRITESYSTEM&redirect_uri=https://hp-net.github.io/homebridge-nibe/nibe.html&state=1678725766904 replace XXXXX with your client id. You can use my redirect uri but you need to configure it also during key and secret generation. Redirect uri is just simple static page and it is safe to use it, I will not use, store or do anything with your data. If you need more help I can paste configuration how to from plugin configuration page.

**Comment by hpruszyn** [comment]
If you have some tech skills you can try to read instruction from https://github.com/hp-net/homebridge-nibe/blob/main/homebridge-ui/public/index.html. If not I can paste screenshots.

**Comment by Stanly001CZ** [comment]
If you'd be so kind, I'd appreciate some screenshots. My skills are not as good as I would like and this looks very complicated for my knowledge. Thank you ! Auth code works :-)

**Comment by hpruszyn** [comment]
<img width="761" alt="image" src="https://user-images.githubusercontent.com/9249677/225083525-6851d6bb-0dab-4328-bb55-610a2c765b8d.png">

ACCOUNT: https://www.nibeuplink.com/
API ACCOUNT: https://api.nibeuplink.com/Account/LogIn
GENERATE AUTH CODE: https://api.nibeuplink.com/oauth/authorize?response_type=code&client_id=XXXXXXX&scope=READSYSTEM%20WRITESYSTEM&redirect_uri=https://hp-net.github.io/homebridge-nibe/nibe.html&state=1678813756046
