### ISSUE TITLE
Which heat pumps (or series) are supported?

### ISSUE THREAD

**Issue by konki-vienna** [hp-net/homebridge-nibe#182]
Can you provide a list of Nibe heat pumps that are supported by your plugin?
It looks like your plugin would support only the F-series. I tried to follow your guide with my S-series heat pump (which I can control) via https://myuplink.com/, but failed to connect it via the URL in your setup guide.

**Comment by hpruszyn** [comment]
Hi, I think that your question is related to https://github.com/hp-net/homebridge-nibe/discussions/114. Long story short: plug-in supports all devices that return data via old uplink api. If new my uplink api will support older devices I will consider switch.

**Comment by auburn-pensive0o** [comment]
At least F750 now supports the new myuplink api, probably the f470 also

**Comment by hpruszyn** [comment]
MyUplink is now supported.
