### ISSUE TITLE
Support for new portal myuplink.com

### ISSUE THREAD

**Issue by ristridin01** [hp-net/homebridge-nibe#185]
Nibe published new firmware versions that allow older VVM devices to connect to the new myuplink portal, nibeuplink.com is deprecrated.
New api endpoint is now api.myuplink.com.
Great about this change is that many more devices are accessible now through this new api.
Could you have a look into this to see what effort it would mean to update the plugin to this new api?

Kind regards!
Ristridin

**Comment by failbit** [comment]
+1

**Comment by nseries100** [comment]
+1

**Comment by hpruszyn** [comment]
My F1145 has finally been migrated to myuplink, so I can begin implementing it 😃🎉 Stay tuned! 😉

**Comment by marco74hh** [comment]
Hi, my new VMM S320 (running on 3.0.10) with a S2125-8 has been installed 2 weeks ago. It is connected to myuplink and both premium add-ons are activated, since they were included after registration. I am not a developer, but an IT systems integrator, so if you need any testing or feedback feel free to contact me.

**Comment by hpruszyn** [comment]
API replacement and refactoring of the plugin is done. I will update the unit tests and release the "beta" version soon. The "beta" will contain only temperature sensors.

**Comment by MichaelPlank** [comment]
Thanks @hpruszyn for working on an update to support the new myuplink portal. 
Any news on when a beta version will be available?

**Comment by hpruszyn** [comment]
The first release with temperature sensors is done. The next one will be related to hot water accessory #231.
