### ISSUE TITLE
Plugin GUI incomplete

### ISSUE THREAD

**Issue by ristridin01** [hp-net/homebridge-nibe#3]
Hi Hubert,

there seems to be a slight bug, cause the boxes for pasting the needed informations are missing.
I attached two screenshots.

**Versions**
Plugin version: 0.0.5
Node version: 16.14.2
Operating system: Alpine LInux (3.2.11)

Greetings,
Boris

![Screenshot 2022-04-05 132111](https://user-images.githubusercontent.com/11363710/161743200-ac55d3ab-7537-400a-8977-ad3cbdbe2440.jpg)
![Screenshot 2022-04-05 132059](https://user-images.githubusercontent.com/11363710/161743201-e1312b75-3890-4e59-96ea-d14eaaba7058.jpg)

**Comment by hpruszyn** [comment]
Few questions:

1. What browser are you using? 
3. Do you have any errors in the browser (Console in Programming Tools)?
4. Can you try in different browser or incognito/private mode?
5. Can you clear browser cache and try again?

Form is rendered by homebridge java script functionality: https://developers.homebridge.io/#/custom-plugin-ui#homebridgeshowschemaform. Only top part with buttons and setup instructions are custom made.

**Comment by ristridin01** [comment]
1. MS Edge Version 100.0.1185.29 (Offizielles Build) (64-Bit)
2. Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'callbackUrl')
    at index.html?origin=http%3A%2F%2F192.168.1.11%3A8581&v=0.0.5:115:32
(anonym) @ index.html?origin=http%3A%2F%2F192.168.1.11%3A8581&v=0.0.5:115
setInterval (asynchron)
(anonym) @ index.html?origin=http%3A%2F%2F192.168.1.11%3A8581&v=0.0.5:111
await in (anonym) (asynchron)
(anonym) @ index.html?origin=http%3A%2F%2F192.168.1.11%3A8581&v=0.0.5:127
index.html?origin=http%3A%2F%2F192.168.1.11%3A8581&v=0.0.5:115 
3. Error occures in private and normal mode
4. same behavior with Firefox

**Comment by hpruszyn** [comment]
Can you uninstall plugin and install it again (make sure to also remove it from configuration)? I've changed some names between version 0.0.4 and 0.0.5 to make it similar to nibe naming convention, e.g.: `redirect` was changed to `callbackUrl`.

**Comment by ristridin01** [comment]
I startet with 0.0.5 already, but tried the uinstall nevertheless;
but no change, still no input boxes available.

**Comment by hpruszyn** [comment]
OK, I know when the problem may be, I'll try to release fix today.

**Comment by hpruszyn** [comment]
Reproduced locally, fixed and tested on local computer. Waiting for release.

**Comment by ristridin01** [comment]
confirm the fix, gui is working now 👍
