### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by ristridin01** [hp-net/homebridge-nibe#4]
It would be great for the future to be able to add some or all of the following values:

- water temperature
- working mode (heating, water heating, cooling)
- temperatures in/out
- number of starts

Cheers,
Boris

**Comment by ristridin01** [comment]
reading through the api, one hot_water_temperature seems to be available.

**Comment by hpruszyn** [comment]
Hot water (maybe with 'enable temporary lux') and ERS (recuperation) are on my todo list.

My setup is F1145-10 PC with ERS 10-400.

**Comment by hpruszyn** [comment]
Hot water is done.

**Comment by ristridin01** [comment]
> My setup is F1145-10 PC with ERS 10-400.

My setup is F2120-12 & VVM500, just opend a new product issue with my actual homebridge log. :)

**Comment by hpruszyn** [comment]
I will close this issue and move new accessories request to separate issues.
