### ISSUE TITLE
Missing parameters for F370, F470, F730 and F750. 

### ISSUE THREAD

**Issue by zlugg** [hp-net/homebridge-nibe#74]
F370, F470, F730 and F750 are exhaust air heat pumps. 
They can get some parameters without an ERS accessory.

I am missing some parameters: 47260 "Selected Fan speed" or preferably 10001 "fan speed" because of a function called "night cooling" which can force the "fan speed 4" to be activated to cool the house.
And sensors: 40025 "exhaust air" and 40026 "extract air".

**Comment by hpruszyn** [comment]
@zlugg can you provide response from nibe uplink api?

I also have night cooling enabled and it is not affecting any parameters. Did you buy premium subscription for managing your Nibe device?

**Comment by zlugg** [comment]
@hpruszyn Sorry, misunderstanding of the documentation. Sensors: 40025 "exhaust air" and 40026 "extract air" are working (called: "ers-exhaust-air" and "ers-extract-air" in config file). "exhaust air" is intresting as an average temperature of the house.

**Comment by zlugg** [comment]
43084 "electrical addition power" could also be interesting as an indicator for when to start up additional heat source. If you for example have an air to air heat pump (for cooling in the summer) i should be more economical to run it.

**Comment by hpruszyn** [comment]
> 43084 "electrical addition power" could also be interesting as an indicator for when to start up additional heat source. If you for example have an air to air heat pump (for cooling in the summer) i should be more economical to run it.

For all test data that I have (from logs) this parameter is always 0:
https://github.com/hp-net/homebridge-nibe/tree/main/tests/data

**Comment by zlugg** [comment]
No test data from the winter? It should only be more than zero when the heat pump can't keep the heat in the house without additional heat from direct electrical heat. I have seen it active when it was -10 degrees Celsius.

**Comment by hpruszyn** [comment]
@zlugg please test new ventilation accessory. It should be available for devices you mention, I don't have it so any feedback will be very welcome.
