### ISSUE TITLE
Config values are not saved

### ISSUE THREAD

**Issue by robinjhector** [hp-net/homebridge-nibe#94]
**Describe the bug**
Toggling any of the four parameters in plugin settings, makes no difference (Settings are not saved)
<img width="572" alt="Screenshot 2022-08-21 at 13 42 02" src="https://user-images.githubusercontent.com/28866344/185789223-eeeb9710-d12b-48c5-a5cc-4c6d8348ae39.png">

**To Reproduce**
1. Go to Plugins
2. Click on Settings for Nibe Uplink
3. Scroll down to `Accessories`
4. Try to toggle one of them, and save, restart. Values are not saved

**Expected behavior**
I would have expected the ability to turn off some accessories via config

**Screenshots & Logfiles**
See above

**Versions**
Plugin version: 0.1.2
Node version: Not sure
Operating system: Inside homebridge docker

**Comment by hpruszyn** [comment]
Value was not in schema so Google checkbox was updating config but save button was validating it with schema and removing not existing properties.
I will release it today.

**Comment by hpruszyn** [comment]
v0.1.3 released. @robinjhector please let me know if it works after update or just simply close this issue.
