### ISSUE TITLE
F730 E EM 3x400V

### ISSUE THREAD

**Issue by MSacher** [hp-net/homebridge-nibe#95]
**What sensors/parameters should be supported**
- ...
- ...

**Data from logs**
```
Paste here data from logs
```

**Comment by hpruszyn** [comment]
@MSacher please paste data from logs otherwise I can't check what configuration is needed for your device.

**Comment by MSacher** [comment]
This is the Homebridge log: Aug 18 18:44:17 raspberrypi4 homebridge[4378]: [18.8.2022, 18:44:17] [Nibe] Loading configuration for F730 E EM 3x400VAug 18 18:44:17 raspberrypi4 homebridge[4378]: [18.8.2022, 18:44:17] [Nibe] ENOENT: no such file or directory, open '/usr/local/lib/node_modules/homebridge-nibe/dist/config/F730-E-EM-3x400V.yaml'Aug 18 18:44:17 raspberrypi4 homebridge[4378]: [18.8.2022, 18:44:17] [Nibe] {"errno":-2,"syscall":"open","code":"ENOENT","path":"/usr/local/lib/node_modules/homebridge-nibe/dist/config/F730-E-EM-3x>Aug 18 18:44:17 raspberrypi4 homebridge[4378]: [18.8.2022, 18:44:17] [Nibe] No configuration for F730 E EM 3x400VAug 18 18:44:17 raspberrypi4 homebridge[4378]: [18.8.2022, 18:44:17] [Nibe] Create support issue to support new model, use link: https://github.com/hp-net/homebridge-nibe/issues/new?assignees=&labe>Aug 18 18:44:17 raspberrypi4 homebridge[4378]: [18.8.2022, 18:44:17] [Nibe] {"unitData":[{"systemUnitId":0,"name":"master","shortName":"m","product":"F730 E EM 3x400V","softwareVersion":"9089R12",">  According to Nibe Support, the technical (interface) details are identical to a “F730 CU” Best regards   Von: Hubert Pruszyński ***@***.***>Datum: Montag, 22. August 2022 um 10:41An: hp-net/homebridge-nibe ***@***.***>Cc: MSacher ***@***.***>, Mention ***@***.***>Betreff: Re: [hp-net/homebridge-nibe] F730 E EM 3x400V (Issue ***@***.*** please paste data from logs otherwise I can't check what configuration is needed for your device.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by hpruszyn** [comment]
I've added the same configuration as for F730 CU 3x400V. Please let me know if it works because I didn't do any tests for it and I didn't have api response to check ids. Release in v0.1.4.

**Comment by MSacher** [comment]
For your information: I use Google Translator …I tried it and get the following error messages: Aug 22 14:41:08 raspberrypi4 homebridge[6017]: [22.8.2022, 14:41:08] [Nibe] error from /oauth/tokenAug 22 14:41:08 raspberrypi4 homebridge[6017]: [22.8.2022, 14:41:08] [Nibe] Error: Error: Internal Server Error: "<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>No client with the specified identifier was found.</title>\r\n        <meta name=\"viewport\" content=\"width=device-width\" />\r\n        <style>\r\n         body {font-family:\"Verdana\";font-weight:normal;font-size: .7em;color:black;} \r\n         p {font-family:\"Verdana\";font-weight:normal;color:black;margin-top: -5px}\r\n         b {font-family:\"Verdana\";font-weight:bold;color:black;margin-top: -5px}\r\n         H1 { font-family:\"Verdana\";font-weight:normal;font-size:18pt;color:red }\r\n         H2 { font-family:\"Verdana\";font-weight:normal;font-size:14pt;color:maroon }\r\n         pre {font-family:\"Consolas\",\"Lucida Console\",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}\r\n         .marker {font-weight: bold; color: black;text-decoration: none;}\r\n         .version {color: gray;}\r\n         .error {margin-bottom: 10px;}\r\n         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:pointer; }\r\n         @media screen and (max-width: 639px) {\r\n          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }\r\n         }\r\n         @media screen and (max-width: 479px) {\r\n          pre { width: 280px; }\r\n         }\r\n        </style>\r\n    </head>\r\n\r\n    <body bgcolor=\"white\">\r\n\r\n            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>\r\n\r\n            <h2> <i>No client with the specified identifier was found.</i> </h2></span>\r\n\r\n            <font face=\"Arial, Helvetica, Geneva, SunSans-Regular, sans-serif \">\r\n\r\n            <b> Description: </b>An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.\r\n\r\n            <br><br>\r\n\r\n            <b> Exception Details: </b>System.ArgumentException: No client with the specified identifier was found.<br><br>\r\n\r\n            <b>Source Error:</b> <br><br>\r\n\r\n            <table width=100% bgcolor=\"#ffffcc\">\r\n               <tr>\r\n                  <td>\r\n                      <code>\r\n\r\nAn unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.                      </code>\r\n\r\n                  </td>\r\n               </tr>\r\n            </table>\r\n\r\n            <br>\r\n\r\n            <b>Stack Trace:</b> <br><br>\r\n\r\n            <table width=100% bgcolor=\"#ffffcc\">\r\n               <tr>\r\n                  <td>\r\n                      <code><pre>\r\n\r\n[ArgumentException: No client with the specified identifier was found.]\r\n   Emil.Api.Authorization.AuthorizationServerHost.GetClient(String clientIdentifier) in D:\\a\\1\\s\\Emil.Api\\Authorization\\AuthorizationServerHost.cs:273\r\n   DotNetOpenAuth.OAuth2.ChannelElements.ClientAuthenticationModule.TryAuthenticateClientBySecret(IAuthorizationServerHost authorizationServerHost, String clientIdentifier, String clientSecret) +61\r\n   DotNetOpenAuth.OAuth2.ChannelElements.ClientCredentialMessagePartReader.TryAuthenticateClient(IAuthorizationServerHost authorizationServerHost, AuthenticatedClientRequestBase requestMessage, String&amp; clientIdentifier) +70\r\n   DotNetOpenAuth.OAuth2.ChannelElements.AggregatingClientCredentialReader.TryAuthenticateClient(IAuthorizationServerHost authorizationServerHost, AuthenticatedClientRequestBase requestMessage, String&amp; clientIdentifier) +140\r\n   DotNetOpenAuth.OAuth2.ChannelElements.MessageValidationBindingElement.ProcessIncomingMessage(IProtocolMessage message) +159\r\n   DotNetOpenAuth.Messaging.Channel.ProcessIncomingMessage(IProtocolMessage message) +318\r\n   DotNetOpenAuth.Messaging.Channel.ReadFromRequest(HttpRequestBase httpRequest) +404\r\n   DotNetOpenAuth.Messaging.Channel.TryReadFromRequest(HttpRequestBase httpRequest, TRequest&amp; request) +49\r\n   DotNetOpenAuth.OAuth2.AuthorizationServer.HandleTokenRequest(HttpRequestBase request) +69\r\n   Emil.Api.Tasks.OAuth.TokenTask.Execute(HttpRequestBase request) in D:\\a\\1\\s\\Emil.Api\\Tasks\\OAuth\\TokenTask.cs:32\r\n   Emil.Api.Controllers.OAuthController.Token() in D:\\a\\1\\s\\Emil.Api\\Controllers\\OAuthController.cs:36\r\n   lambda_method(Closure , ControllerBase , Object[] ) +66\r\n   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +19\r\n   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +169\r\n   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27\r\n   System.Web.Mvc.Async.AsyncControllerActionInvoker.&lt;BeginInvokeSynchronousActionMethod&gt;b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +24\r\n   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +31\r\n   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +50\r\n   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +33\r\n   System.Web.Mvc.Async.AsyncInvocationWithFilters.&lt;InvokeActionMethodFilterAsynchronouslyRecursive&gt;b__3d() +50\r\n   System.Web.Mvc.Async.&lt;&gt;c__DisplayClass46.&lt;InvokeActionMethodFilterAsynchronouslyRecursive&gt;b__3f() +228\r\n   System.Web.Mvc.Async.&lt;&gt;c__DisplayClass33.&lt;BeginInvokeActionMethodWithFilters&gt;b__32(IAsyncResult asyncResult) +15\r\n   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +15\r\n   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +50\r\n   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +35\r\n   System.Web.Mvc.Async.&lt;&gt;c__DisplayClass2b.&lt;BeginInvokeAction&gt;b__1c() +26\r\n   System.Web.Mvc.Async.&lt;&gt;c__DisplayClass21.&lt;BeginInvokeAction&gt;b__1e(IAsyncResult asyncResult) +100\r\n   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +15\r\n   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +50\r\n   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +29\r\n   System.Web.Mvc.Controller.&lt;BeginExecuteCore&gt;b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +15\r\n   System.Web.Mvc.Async.WrappedAsyncVoid`1CallEndDelegate(IAsyncResult asyncResult) +29\r\n   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +50\r\n   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36\r\n   System.Web.Mvc.Controller.&lt;BeginExecute&gt;b__15(IAsyncResult asyncResult, Controller controller) +14\r\n   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22\r\n   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +50\r\n   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +27\r\n   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +12\r\n   System.Web.Mvc.MvcHandler.&lt;BeginProcessRequest&gt;b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21\r\n   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29\r\n   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +50\r\n   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +29\r\n   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +11\r\n   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +576\r\n   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +132\r\n   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +163\r\n</pre>             Aug 22 14:41:08 raspberrypi4 homebridge[6017]:     at NibeFetcher.checkError (/usr/local/lib/node_modules/homebridge-nibe/dist/nibe/uplink/nibe-fetcher.js:337:28)Aug 22 14:41:08 raspberrypi4 homebridge[6017]:     at NibeFetcher.postTokenRequest (/usr/local/lib/node_modules/homebridge-nibe/dist/nibe/uplink/nibe-fetcher.js:238:24)Aug 22 14:41:08 raspberrypi4 homebridge[6017]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)Aug 22 14:41:08 raspberrypi4 homebridge[6017]:     at NibeFetcher.getRefreshToken (/usr/local/lib/node_modules/homebridge-nibe/dist/nibe/uplink/nibe-fetcher.js:221:16)Aug 22 14:41:08 raspberrypi4 homebridge[6017]:     at NibeFetcher.fetch (/usr/local/lib/node_modules/homebridge-nibe/dist/nibe/uplink/nibe-fetcher.js:157:31)  And at the end: Aug 22 14:41:13 raspberrypi4 systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/aAug 22 14:41:13 raspberrypi4 systemd[1]: homebridge.service: Failed with result 'exit-code'. … and my homebridge keeps restarting …   Von: Hubert Pruszyński ***@***.***>Datum: Montag, 22. August 2022 um 14:01An: hp-net/homebridge-nibe ***@***.***>Cc: MSacher ***@***.***>, Mention ***@***.***>Betreff: Re: [hp-net/homebridge-nibe] F730 E EM 3x400V (Issue #95)I've added the same configuration as for F730 CU 3x400V. Please let me know if it works because I didn't do any tests for it and I didn't have api response to check ids. Release in v0.1.4.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by hpruszyn** [comment]
@MSacher please post an answer via Github web page. When you answer via email it is not readable.
