### ISSUE TITLE
Wrong reference to file

### ISSUE THREAD

**Issue by Anders57S** [hp-net/homebridge-nibe#96]
Newbie here, so excuse my simple bug report....

When installing the plugin I got an error saying that file: 

...\AppData\Roaming\npm\node_modules\homebridge-nibe\dist\config\F750-CU.yaml can't be found.

The file is (now) named F750-CU-3xx400V.yaml so by changing the name to F750-CU.yaml everything started as expected.

**Comment by hpruszyn** [comment]
During installation it should not happen. After saving configuration with api credential it could happen but then you should see message in logs that this device is not supported and you should crate issue for that with logs from api response. 

F750-CU.yaml I didn't have before but I can add it. However without nibe api response for this device I would not be able to check if new accessories will work with that device or not.

@Anders57S let me know if you can provide api response or not.

**Comment by Anders57S** [comment]
Ok
I am not a very good technician but I reported what i saw in the log.
After changing the name on the file it works and i can see my data in Homebridge so I'm happy.
I'm not sure what you mean with api response, so i guess my answer is "no"...

But, as i mentioned. Everything is working fine now.
